### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by dandv** [rob-blackbourn/jetblack-graphql-client#2]
Hi Rob, I've been looking for a [simple, non-caching, not-React-centric GraphQL client that could handle subscriptions](https://spectrum.chat/apollo/subscriptions/server-to-server-subscription~6595159b-546b-4685-af4d-68f0282c59de) and found your package. Thanks!

While trying to run the example, I'm getting "WebSocket is not defined".

Installing the `websocket` package didn't help.

**Comment by rob-blackbourn** [comment]
Hi Dude,

The WebSicket class is built in to every browser. https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

Are your running it from nodejs?

Rob

**Comment by dandv** [comment]
Yes, I was looking for a server-side client. Too late at night :)

**Comment by rob-blackbourn** [comment]
I’d be interested to know if it works from nodejs :)
